from langchain import agents
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from tools import search_web, scrape_url
from dotenv import load_dotenv

load_dotenv()

# Initialize the Google Gemini model with better free tier support
# Use max_retries=1 to fail fast on quota errors
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",  # Use more stable older model
    temperature=0.3,
    max_retries=1,  # Fail fast on quota errors
    timeout=20
)

# Define a function to build the search agent using the
# Google Gemini model and the search_web tool


def build_search_agent():
    return agents.create_agent(model=llm, tools=[search_web])

# Define a function to build the reader agent using the
# Google Gemini model and the scrape_url tool
# With explicit system prompt to extract and scrape URLs


reader_system_prompt = """You are an expert research content scraper. Your task is to:
1. Identify all URLs mentioned in the search results
2. Scrape each URL using the scrape_url tool to get the full content
3. Return the scraped content WITH the source URLs clearly labeled

IMPORTANT: Always include the source URL in your output for every scraped piece of content.
Format each scraped result as: "Source: [URL]\n[Content]"
"""

def build_reader_agent():
    return agents.create_agent(
        model=llm,
        tools=[scrape_url],
        system_prompt=reader_system_prompt
    )


#
writer_prompt = ChatPromptTemplate.from_messages([
    ('system', 'You are a expert research writer who creates structured, well clear, and insightful reports.'),
    ('human', """Write a detailed research report on the topic below.
        Topic: {topic}
        Research Gathered: {research}
     
        Structure the report as:
        1. Introduction: Briefly introduce the topic and its significance.
        2. Key Findings: Summarize the most important insights and information gathered from the research in points.
        3. Conclusion: Provide a concise conclusion that highlights the overall understanding of the topic based on the research.
        4. References: List the sources, urls of the research information in a clear format.
     
        Ensure the report is well-organized, clear, and provides a comprehensive overview of the topic based on the research provided.
    """)
])

# Combine the prompt, model, and output parser into a chain for the writer agent
writer_chain = writer_prompt | llm | StrOutputParser()

# Define a prompt for the critic agent to evaluate the quality and relevance of the research report generated by the writer agent
critic_prompt = ChatPromptTemplate.from_messages([
    ('system', 'You are a sharp and constructive critical analyst who evaluates the quality and relevance of research reports. Be specific and honest.'),
    ('human', """Evaluate the following research report strictly based on the topic and research provided.

        Report: {report}

        Respond in this exact format:

        1. Score: X/10 (10 being the best)
        2. Strengths: List the specific strengths of the report in points.
        3. Weaknesses: List the specific weaknesses of the report in points.
        4. Suggestions for Improvement: Provide specific and actionable suggestions to improve the report in points.
        5. One line verdict: Provide a concise one-line summary of your overall evaluation of the report.

        Be detailed and specific in your evaluation, providing clear feedback on how to enhance the quality and relevance of the research report.
    """)
])

critic_chain = critic_prompt | llm | StrOutputParser()